baseURL = "https://honeyprintshop.com/"
languageCode = "en-us"
title = "Honey Print Shop"
enableRobotsTXT = true

[params]
  description = "Welcome to Honey Print Shop, your go-to place for beautiful prints."
  author = "Jake & Rozlynn" 
  keywords = ["prints", "art"]

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/willfaught/paige"

[markup.goldmark.renderer]
unsafe = true

[params.paige.site]
disable_breadcrumbs = true
color = "#DECCA6" # Bootstrap primary color and theme color for Safari and Windows
color_scheme = "auto" # Must be "auto", "dark", or "light"
keyword_style = "text" # Must be "text" or "pills"
menu_style = "tabs" # Must be "links", "pills", "tabs", or "underline"
disable_credit = true
description = "Designed by Us, Inspired by Life"


[outputs]
home = ["html"]

[params.paige.pages]
disable_authors = true
disable_collections = true
disable_date = true
disable_description = false
disable_edit = true
disable_history = true
disable_keywords = false
disable_next = true
disable_prev = true
disable_reading_time = true
disable_sections = true
disable_series = true
disable_toc = true
disable_word_count = true
disable_title = true
disable_pages = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[params.paige]
style = """
#paige-page-content,
#paige-page-pages > * { margin-left: auto; margin-right: auto; max-width: 40rem; }
#paige-page-content > img,
#paige-page-content > .paige-shortcode-image,
#paige-page-content > .paige-shortcode-vimeo,
#paige-page-content > .paige-shortcode-youtube { max-width: 100%; }
"""


[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10



